[2025-04-14T03:50:06.983+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T03:50:06.998+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T03:50:07.006+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T03:50:07.006+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T03:50:07.016+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): merge_tables_task> on 2025-04-13 00:00:00+00:00
[2025-04-14T03:50:07.021+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T03:50:07.023+0000] {standard_task_runner.py:72} INFO - Started process 147 to run task
[2025-04-14T03:50:07.023+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'merge_tables_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpkd4cpowk']
[2025-04-14T03:50:07.024+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask merge_tables_task
[2025-04-14T03:50:07.050+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host f7261677844c
[2025-04-14T03:50:07.089+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='merge_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T03:50:07.091+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T03:50:07.091+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T03:50:07.091+0000] {logging_mixin.py:190} INFO - Current task name:merge_tables_task state:running start_date:2025-04-14 03:50:06.998733+00:00
[2025-04-14T03:50:07.091+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T03:50:07.091+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T03:50:07.092+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T03:50:07.092+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T03:50:07.093+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T03:50:07.121+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          MERGE INTO `nyc-projects-455321.building_permits.permits` T\n          USING `nyc-projects-455321.building_permits.temp_table` S\n          ON T.job_type = S.job_type\n          WHEN NOT MATCHED THEN\n            INSERT (borough, job_type, block, lot, issuance_date, permit_si_no, gis_latitude, gis_longitude, gis_nta_name)\n            VALUES (S.borough, S.job_type, S.block, S.lot, S.issuance_date, S.permit_si_no, S.gis_latitude, S.gis_longitude, S.gis_nta_name);\n        ', 'useLegacySql': False}}'
[2025-04-14T03:50:07.122+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_56203c594a60a4b9ad4daf54f501b345
[2025-04-14T03:50:10.506+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_56203c594a60a4b9ad4daf54f501b345 is completed. Checking the job status
[2025-04-14T03:50:10.549+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T03:50:10.550+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=merge_tables_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T035006, end_date=20250414T035010
[2025-04-14T03:50:10.570+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-14T03:50:10.571+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-14T03:50:10.571+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-14 03:49:43.644379+00:00
[2025-04-14T03:50:10.571+0000] {logging_mixin.py:190} INFO - Task hostname:f7261677844c operator:BigQueryInsertJobOperator
[2025-04-14T03:50:10.611+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-14T03:50:10.635+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T03:50:10.637+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T03:57:55.115+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T03:57:55.131+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T03:57:55.138+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T03:57:55.139+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T03:57:55.145+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): merge_tables_task> on 2025-04-13 00:00:00+00:00
[2025-04-14T03:57:55.149+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T03:57:55.150+0000] {standard_task_runner.py:72} INFO - Started process 153 to run task
[2025-04-14T03:57:55.150+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'merge_tables_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpgdqoi0sj']
[2025-04-14T03:57:55.151+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask merge_tables_task
[2025-04-14T03:57:55.175+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host 3029200567a0
[2025-04-14T03:57:55.213+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='merge_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T03:57:55.214+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T03:57:55.215+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T03:57:55.215+0000] {logging_mixin.py:190} INFO - Current task name:merge_tables_task state:running start_date:2025-04-14 03:57:55.132227+00:00
[2025-04-14T03:57:55.215+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T03:57:55.215+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T03:57:55.216+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T03:57:55.216+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T03:57:55.217+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T03:57:55.245+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          MERGE INTO `nyc-projects-455321.building_permits.permits` T\n          USING `nyc-projects-455321.building_permits.temp_table` S\n          ON T.job_type = S.job_type\n          WHEN NOT MATCHED THEN\n            INSERT (borough, job_type, block, lot, issuance_date, permit_si_no, gis_latitude, gis_longitude, gis_nta_name)\n            VALUES (S.borough, S.job_type, S.block, S.lot, S.issuance_date, S.permit_si_no, S.gis_latitude, S.gis_longitude, S.gis_nta_name);\n        ', 'useLegacySql': False}}'
[2025-04-14T03:57:55.245+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_12397c8c5b6eb14e6db604b561d96caf
[2025-04-14T03:57:58.768+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_12397c8c5b6eb14e6db604b561d96caf is completed. Checking the job status
[2025-04-14T03:57:58.788+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T03:57:58.789+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=merge_tables_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T035755, end_date=20250414T035758
[2025-04-14T03:57:58.812+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-14T03:57:58.813+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-14T03:57:58.813+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-14 03:57:32.901326+00:00
[2025-04-14T03:57:58.813+0000] {logging_mixin.py:190} INFO - Task hostname:3029200567a0 operator:BigQueryInsertJobOperator
[2025-04-14T03:57:58.859+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-14T03:57:58.901+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T03:57:58.903+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T04:14:51.975+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T04:14:51.986+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T04:14:51.992+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T04:14:51.992+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T04:14:51.998+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): merge_tables_task> on 2025-04-13 00:00:00+00:00
[2025-04-14T04:14:52.003+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T04:14:52.003+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2025-04-14T04:14:52.004+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'merge_tables_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4aj5jwl6']
[2025-04-14T04:14:52.005+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask merge_tables_task
[2025-04-14T04:14:52.030+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host e86210162b75
[2025-04-14T04:14:52.070+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='merge_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T04:14:52.072+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T04:14:52.072+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T04:14:52.072+0000] {logging_mixin.py:190} INFO - Current task name:merge_tables_task state:running start_date:2025-04-14 04:14:51.987057+00:00
[2025-04-14T04:14:52.072+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T04:14:52.072+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T04:14:52.073+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T04:14:52.073+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T04:14:52.074+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T04:14:52.102+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          MERGE INTO `nyc-projects-455321.building_permits.permits` T\n          USING `nyc-projects-455321.building_permits.temp_table` S\n          ON T.job_type = S.job_type\n          WHEN NOT MATCHED THEN\n            INSERT (borough, job_type, block, lot, issuance_date, permit_si_no, location_coordinates, gis_nta_name)\n            VALUES (S.borough, S.job_type, S.block, S.lot, S.issuance_date, S.permit_si_no, S.location_coordinates, S.gis_nta_name);\n        ', 'useLegacySql': False}}'
[2025-04-14T04:14:52.102+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5594c389ea1db8c48d1f8ffb981ec7ef
[2025-04-14T04:14:52.953+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Name location_coordinates not found inside S at [7:95]; reason: invalidQuery, location: query, message: Name location_coordinates not found inside S at [7:95]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5594c389ea1db8c48d1f8ffb981ec7ef

[2025-04-14T04:14:52.986+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T04:14:52.987+0000] {logging_mixin.py:190} INFO - Task start:2025-04-14 04:14:51.987057+00:00 end:2025-04-14 04:14:52.985537+00:00 duration:0.99848
[2025-04-14T04:14:52.989+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryInsertJobOperator): merge_tables_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-13 00:00:00+00:00: scheduled__2025-04-13T00:00:00+00:00, state:running, queued_at: 2025-04-14 04:14:28.657183+00:00. externally triggered: False>
[2025-04-14T04:14:52.989+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Name location_coordinates not found inside S at [7:95]; reason: invalidQuery, location: query, message: Name location_coordinates not found inside S at [7:95]

Location: US
Job ID: ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5594c389ea1db8c48d1f8ffb981ec7ef
[2025-04-14T04:14:52.990+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=merge_tables_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T041451, end_date=20250414T041452
[2025-04-14T04:14:53.049+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T04:14:53.051+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task merge_tables_task (400 Name location_coordinates not found inside S at [7:95]; reason: invalidQuery, location: query, message: Name location_coordinates not found inside S at [7:95]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5594c389ea1db8c48d1f8ffb981ec7ef
; 112)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Name location_coordinates not found inside S at [7:95]; reason: invalidQuery, location: query, message: Name location_coordinates not found inside S at [7:95]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5594c389ea1db8c48d1f8ffb981ec7ef

[2025-04-14T04:14:53.085+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T04:14:53.102+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T04:14:53.103+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T04:17:03.459+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T04:17:03.470+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T04:17:03.477+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T04:17:03.477+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T04:17:03.483+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): merge_tables_task> on 2025-04-13 00:00:00+00:00
[2025-04-14T04:17:03.487+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T04:17:03.488+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2025-04-14T04:17:03.489+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'merge_tables_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpy30gkc_0']
[2025-04-14T04:17:03.489+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask merge_tables_task
[2025-04-14T04:17:03.521+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host d054e5caec0f
[2025-04-14T04:17:03.561+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='merge_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T04:17:03.563+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T04:17:03.563+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T04:17:03.563+0000] {logging_mixin.py:190} INFO - Current task name:merge_tables_task state:running start_date:2025-04-14 04:17:03.470593+00:00
[2025-04-14T04:17:03.563+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T04:17:03.563+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T04:17:03.564+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T04:17:03.565+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T04:17:03.565+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T04:17:03.593+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          MERGE INTO `nyc-projects-455321.building_permits.permits` T\n          USING `nyc-projects-455321.building_permits.temp_table` S\n          ON T.job_type = S.job_type\n          WHEN NOT MATCHED THEN\n            INSERT (borough, job_type, block, lot, issuance_date, permit_si_no, location_coordinates, gis_nta_name)\n            VALUES (S.borough, S.job_type, S.block, S.lot, S.issuance_date, S.permit_si_no, S.location_coordinates, S.gis_nta_name);\n        ', 'useLegacySql': False}}'
[2025-04-14T04:17:03.594+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_ecc7f8487e26631442d19d3cb155954f
[2025-04-14T04:17:06.675+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_ecc7f8487e26631442d19d3cb155954f is completed. Checking the job status
[2025-04-14T04:17:06.718+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T04:17:06.720+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=merge_tables_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T041703, end_date=20250414T041706
[2025-04-14T04:17:06.761+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-14T04:17:06.762+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-14T04:17:06.763+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-14 04:16:38.268960+00:00
[2025-04-14T04:17:06.763+0000] {logging_mixin.py:190} INFO - Task hostname:d054e5caec0f operator:BigQueryInsertJobOperator
[2025-04-14T04:17:06.788+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-14T04:17:06.824+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T04:17:06.826+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T05:28:26.335+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T05:28:26.348+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T05:28:26.354+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T05:28:26.354+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T05:28:26.360+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): merge_tables_task> on 2025-04-13 00:00:00+00:00
[2025-04-14T05:28:26.364+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T05:28:26.365+0000] {standard_task_runner.py:72} INFO - Started process 139 to run task
[2025-04-14T05:28:26.366+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'merge_tables_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpp714c2pt']
[2025-04-14T05:28:26.366+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask merge_tables_task
[2025-04-14T05:28:26.393+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host 26629b401d8b
[2025-04-14T05:28:26.435+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='merge_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T05:28:26.438+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T05:28:26.438+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T05:28:26.438+0000] {logging_mixin.py:190} INFO - Current task name:merge_tables_task state:running start_date:2025-04-14 05:28:26.348466+00:00
[2025-04-14T05:28:26.438+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T05:28:26.438+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T05:28:26.439+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T05:28:26.439+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T05:28:26.441+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T05:28:26.491+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          MERGE INTO `nyc-projects-455321.building_permits.permits` T\n          USING `nyc-projects-455321.building_permits.temp_table` S\n          ON T.job_type = S.job_type\n          WHEN NOT MATCHED THEN\n            INSERT (borough, job_type, block, lot, issuance_date, permit_si_no, location_coordinates, gis_nta_name)\n            VALUES (S.borough, S.job_type, S.block, S.lot, S.issuance_date, S.permit_si_no, S.location_coordinates, S.gis_nta_name);\n        ', 'useLegacySql': False}}'
[2025-04-14T05:28:26.493+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5c90e92ce2c401da30ba29abba7af0e1
[2025-04-14T05:28:29.913+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_5c90e92ce2c401da30ba29abba7af0e1 is completed. Checking the job status
[2025-04-14T05:28:29.927+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T05:28:29.927+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=merge_tables_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T052826, end_date=20250414T052829
[2025-04-14T05:28:29.939+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-14T05:28:29.940+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-14T05:28:29.940+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-14 05:27:28.560179+00:00
[2025-04-14T05:28:29.940+0000] {logging_mixin.py:190} INFO - Task hostname:26629b401d8b operator:BigQueryInsertJobOperator
[2025-04-14T05:28:29.948+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-14T05:28:29.959+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T05:28:29.962+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T05:49:34.974+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T05:49:34.984+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T05:49:34.990+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T05:49:34.990+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T05:49:34.996+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): merge_tables_task> on 2025-04-13 00:00:00+00:00
[2025-04-14T05:49:35.000+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=369) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T05:49:35.001+0000] {standard_task_runner.py:72} INFO - Started process 371 to run task
[2025-04-14T05:49:35.001+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'merge_tables_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp09b5sw_c']
[2025-04-14T05:49:35.002+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask merge_tables_task
[2025-04-14T05:49:35.026+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.merge_tables_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host 51652b031d9f
[2025-04-14T05:49:35.063+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='merge_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T05:49:35.064+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T05:49:35.064+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T05:49:35.064+0000] {logging_mixin.py:190} INFO - Current task name:merge_tables_task state:running start_date:2025-04-14 05:49:34.985098+00:00
[2025-04-14T05:49:35.064+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T05:49:35.064+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T05:49:35.065+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T05:49:35.065+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T05:49:35.066+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T05:49:35.093+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          MERGE INTO `nyc-projects-455321.building_permits.permits` T\n          USING `nyc-projects-455321.building_permits.temp_table` S\n          ON T.job_type = S.job_type\n          WHEN NOT MATCHED THEN\n            INSERT (borough, job_type, block, lot, issuance_date, permit_si_no, location_coordinates, gis_nta_name)\n            VALUES (S.borough, S.job_type, S.block, S.lot, S.issuance_date, S.permit_si_no, S.location_coordinates, S.gis_nta_name);\n        ', 'useLegacySql': False}}'
[2025-04-14T05:49:35.094+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_0d27c101e2575db1e43f106f802f48b8
[2025-04-14T05:49:42.624+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_merge_tables_task_2025_04_13T00_00_00_00_00_0d27c101e2575db1e43f106f802f48b8 is completed. Checking the job status
[2025-04-14T05:49:42.681+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T05:49:42.682+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=merge_tables_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T054934, end_date=20250414T054942
[2025-04-14T05:49:42.715+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-14T05:49:42.716+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-14T05:49:42.716+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-14 05:31:46.685490+00:00
[2025-04-14T05:49:42.716+0000] {logging_mixin.py:190} INFO - Task hostname:51652b031d9f operator:BigQueryInsertJobOperator
[2025-04-14T05:49:42.752+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-14T05:49:42.780+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T05:49:42.781+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
