[2025-04-13T01:37:54.510+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T01:37:54.521+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T01:37:54.526+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T01:37:54.526+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T01:37:54.533+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_last_issuance_date_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T01:37:54.539+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T01:37:54.540+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2025-04-13T01:37:54.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'get_last_issuance_date_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpwpp_hnln']
[2025-04-13T01:37:54.541+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_last_issuance_date_task
[2025-04-13T01:37:54.576+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 84d0237d7c17
[2025-04-13T01:37:54.621+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='get_last_issuance_date_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T01:37:54.622+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T01:37:54.622+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T01:37:54.622+0000] {logging_mixin.py:190} INFO - Current task name:get_last_issuance_date_task state:running start_date:2025-04-13 01:37:54.522045+00:00
[2025-04-13T01:37:54.623+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T01:37:54.623+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T01:37:55.162+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in get_last_issuance_date
    rows = query_job.result()  # Waits for query to finish
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]; reason: invalidQuery, location: query, message: Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]

Location: US
Job ID: 463e7ee7-e018-4a75-becf-3dda0f35e18a

[2025-04-13T01:37:55.192+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T01:37:55.193+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 01:37:54.522045+00:00 end:2025-04-13 01:37:55.192243+00:00 duration:0.670198
[2025-04-13T01:37:55.194+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_last_issuance_date_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-12 00:00:00+00:00: scheduled__2025-04-12T00:00:00+00:00, state:running, queued_at: 2025-04-13 01:37:51.855652+00:00. externally triggered: False>
[2025-04-13T01:37:55.194+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]; reason: invalidQuery, location: query, message: Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]

Location: US
Job ID: 463e7ee7-e018-4a75-becf-3dda0f35e18a
[2025-04-13T01:37:55.194+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=get_last_issuance_date_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T013754, end_date=20250413T013755
[2025-04-13T01:37:55.213+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T01:37:55.214+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task get_last_issuance_date_task (400 Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]; reason: invalidQuery, location: query, message: Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]

Location: US
Job ID: 463e7ee7-e018-4a75-becf-3dda0f35e18a
; 88)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in get_last_issuance_date
    rows = query_job.result()  # Waits for query to finish
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]; reason: invalidQuery, location: query, message: Syntax error: Expected end of input but got identifier "BIGQUERY_DATASETWHERE" at [1:43]

Location: US
Job ID: 463e7ee7-e018-4a75-becf-3dda0f35e18a

[2025-04-13T01:37:55.255+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T01:37:55.291+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T01:37:55.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T02:45:18.405+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T02:45:18.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T02:45:18.420+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T02:45:18.420+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T02:45:18.426+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_last_issuance_date_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T02:45:18.431+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T02:45:18.432+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2025-04-13T02:45:18.433+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'get_last_issuance_date_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmphuyylt4b']
[2025-04-13T02:45:18.433+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_last_issuance_date_task
[2025-04-13T02:45:18.465+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 84c96c34f493
[2025-04-13T02:45:18.513+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='get_last_issuance_date_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T02:45:18.514+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T02:45:18.514+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T02:45:18.514+0000] {logging_mixin.py:190} INFO - Current task name:get_last_issuance_date_task state:running start_date:2025-04-13 02:45:18.416330+00:00
[2025-04-13T02:45:18.514+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T02:45:18.514+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T02:45:18.934+0000] {python.py:240} INFO - Done. Returned value was: 1997-11-26T00:00:00.000
[2025-04-13T02:45:18.954+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T02:45:18.955+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=get_last_issuance_date_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T024518, end_date=20250413T024518
[2025-04-13T02:45:18.978+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-13T02:45:18.978+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-13T02:45:18.980+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-13 02:45:15.803784+00:00
[2025-04-13T02:45:18.980+0000] {logging_mixin.py:190} INFO - Task hostname:84c96c34f493 operator:PythonOperator
[2025-04-13T02:45:19.022+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T02:45:19.067+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-13T02:45:19.068+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T03:03:07.870+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T03:03:07.879+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T03:03:07.889+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T03:03:07.889+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T03:03:07.898+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_last_issuance_date_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T03:03:07.904+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T03:03:07.905+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2025-04-13T03:03:07.905+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'get_last_issuance_date_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9nijke14']
[2025-04-13T03:03:07.906+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_last_issuance_date_task
[2025-04-13T03:03:07.931+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 198303a87d4f
[2025-04-13T03:03:07.970+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='get_last_issuance_date_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T03:03:07.971+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T03:03:07.971+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T03:03:07.971+0000] {logging_mixin.py:190} INFO - Current task name:get_last_issuance_date_task state:running start_date:2025-04-13 03:03:07.879719+00:00
[2025-04-13T03:03:07.971+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T03:03:07.971+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T03:03:08.352+0000] {python.py:240} INFO - Done. Returned value was: 1997-11-26T00:00:00.000
[2025-04-13T03:03:08.420+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T03:03:08.421+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=get_last_issuance_date_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T030307, end_date=20250413T030308
[2025-04-13T03:03:08.460+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-13T03:03:08.461+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-13T03:03:08.461+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-13 03:03:05.231424+00:00
[2025-04-13T03:03:08.461+0000] {logging_mixin.py:190} INFO - Task hostname:198303a87d4f operator:PythonOperator
[2025-04-13T03:03:08.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T03:03:08.526+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-13T03:03:08.527+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T03:09:12.929+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T03:09:12.938+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T03:09:12.942+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T03:09:12.942+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T03:09:12.948+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_last_issuance_date_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T03:09:12.953+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T03:09:12.954+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2025-04-13T03:09:12.955+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'get_last_issuance_date_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpukc96wvc']
[2025-04-13T03:09:12.956+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_last_issuance_date_task
[2025-04-13T03:09:12.992+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host c02a160e6d99
[2025-04-13T03:09:13.040+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='get_last_issuance_date_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T03:09:13.042+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T03:09:13.042+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T03:09:13.042+0000] {logging_mixin.py:190} INFO - Current task name:get_last_issuance_date_task state:running start_date:2025-04-13 03:09:12.938563+00:00
[2025-04-13T03:09:13.043+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T03:09:13.043+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T03:09:13.463+0000] {python.py:240} INFO - Done. Returned value was: 1997-11-26T00:00:00.000
[2025-04-13T03:09:13.488+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T03:09:13.489+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=get_last_issuance_date_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T030912, end_date=20250413T030913
[2025-04-13T03:09:13.512+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-13T03:09:13.512+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-13T03:09:13.512+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-13 03:09:10.289015+00:00
[2025-04-13T03:09:13.513+0000] {logging_mixin.py:190} INFO - Task hostname:c02a160e6d99 operator:PythonOperator
[2025-04-13T03:09:13.545+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T03:09:13.590+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-13T03:09:13.592+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T03:19:37.643+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T03:19:37.651+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T03:19:37.655+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T03:19:37.655+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T03:19:37.661+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_last_issuance_date_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T03:19:37.665+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T03:19:37.666+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2025-04-13T03:19:37.666+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'get_last_issuance_date_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmppmd7p_xt']
[2025-04-13T03:19:37.667+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_last_issuance_date_task
[2025-04-13T03:19:37.694+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.get_last_issuance_date_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 1b4e74840e23
[2025-04-13T03:19:37.732+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='get_last_issuance_date_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T03:19:37.733+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T03:19:37.733+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T03:19:37.733+0000] {logging_mixin.py:190} INFO - Current task name:get_last_issuance_date_task state:running start_date:2025-04-13 03:19:37.651936+00:00
[2025-04-13T03:19:37.733+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T03:19:37.734+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T03:19:38.114+0000] {python.py:240} INFO - Done. Returned value was: 1997-11-26T00:00:00.000
[2025-04-13T03:19:38.159+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T03:19:38.160+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=get_last_issuance_date_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T031937, end_date=20250413T031938
[2025-04-13T03:19:38.212+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-13T03:19:38.212+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-13T03:19:38.213+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-13 03:19:35.051757+00:00
[2025-04-13T03:19:38.213+0000] {logging_mixin.py:190} INFO - Task hostname:1b4e74840e23 operator:PythonOperator
[2025-04-13T03:19:38.258+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T03:19:38.283+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-13T03:19:38.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
