[2025-04-14T05:01:04.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T05:01:04.840+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-14T04:47:21.222286+00:00 [queued]>
[2025-04-14T05:01:04.844+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-14T04:47:21.222286+00:00 [queued]>
[2025-04-14T05:01:04.844+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T05:01:04.852+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): fetch_permits_task> on 2025-04-14 04:47:21.222286+00:00
[2025-04-14T05:01:04.856+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T05:01:04.857+0000] {standard_task_runner.py:72} INFO - Started process 286 to run task
[2025-04-14T05:01:04.857+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'fetch_permits_task', 'manual__2025-04-14T04:47:21.222286+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpsilh6kor']
[2025-04-14T05:01:04.858+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask fetch_permits_task
[2025-04-14T05:01:04.880+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-14T04:47:21.222286+00:00 [running]> on host 8f3f7397b438
[2025-04-14T05:01:04.916+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='fetch_permits_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T04:47:21.222286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T04:47:21.222286+00:00'
[2025-04-14T05:01:04.918+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T05:01:04.918+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T05:01:04.918+0000] {logging_mixin.py:190} INFO - Current task name:fetch_permits_task state:running start_date:2025-04-14 05:01:04.840626+00:00
[2025-04-14T05:01:04.918+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T05:01:04.918+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T05:01:04.918+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-14T05:01:04.926+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-04-29 (offset=0)
[2025-04-14T05:01:05.901+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-04-30 (offset=0)
[2025-04-14T05:01:06.269+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-01 (offset=0)
[2025-04-14T05:01:06.603+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-02 (offset=0)
[2025-04-14T05:01:06.901+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-03 (offset=0)
[2025-04-14T05:01:07.236+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-04 (offset=0)
[2025-04-14T05:01:07.595+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-05 (offset=0)
[2025-04-14T05:01:07.949+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-06 (offset=0)
[2025-04-14T05:01:08.323+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-07 (offset=0)
[2025-04-14T05:01:08.655+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-08 (offset=0)
[2025-04-14T05:01:09.055+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-09 (offset=0)
[2025-04-14T05:01:09.358+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-10 (offset=0)
[2025-04-14T05:01:09.662+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-11 (offset=0)
[2025-04-14T05:01:13.145+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-12 (offset=0)
[2025-04-14T05:01:13.490+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-13 (offset=0)
[2025-04-14T05:01:13.834+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-14 (offset=0)
[2025-04-14T05:01:14.194+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-15 (offset=0)
[2025-04-14T05:01:14.526+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-16 (offset=0)
[2025-04-14T05:01:14.861+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-17 (offset=0)
[2025-04-14T05:01:14.999+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-18 (offset=0)
[2025-04-14T05:01:15.336+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-19 (offset=0)
[2025-04-14T05:01:15.644+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-20 (offset=0)
[2025-04-14T05:01:15.998+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-21 (offset=0)
[2025-04-14T05:01:16.313+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-22 (offset=0)
[2025-04-14T05:01:16.669+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-23 (offset=0)
[2025-04-14T05:01:16.966+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-24 (offset=0)
[2025-04-14T05:01:17.106+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-25 (offset=0)
[2025-04-14T05:01:17.438+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-26 (offset=0)
[2025-04-14T05:01:17.782+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-27 (offset=0)
[2025-04-14T05:01:18.137+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-28 (offset=0)
[2025-04-14T05:01:18.493+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-29 (offset=0)
[2025-04-14T05:01:18.846+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-30 (offset=0)
[2025-04-14T05:01:19.152+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-31 (offset=0)
[2025-04-14T05:01:19.445+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-01 (offset=0)
[2025-04-14T05:01:19.801+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-02 (offset=0)
[2025-04-14T05:01:20.163+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-03 (offset=0)
[2025-04-14T05:01:20.526+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-04 (offset=0)
[2025-04-14T05:01:20.931+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-05 (offset=0)
[2025-04-14T05:01:24.122+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-06 (offset=0)
[2025-04-14T05:01:24.419+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-07 (offset=0)
[2025-04-14T05:01:24.711+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-08 (offset=0)
[2025-04-14T05:01:25.189+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-09 (offset=0)
[2025-04-14T05:01:25.575+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-10 (offset=0)
[2025-04-14T05:01:25.953+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-11 (offset=0)
[2025-04-14T05:01:26.382+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-12 (offset=0)
[2025-04-14T05:01:26.751+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-13 (offset=0)
[2025-04-14T05:01:27.075+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-14 (offset=0)
[2025-04-14T05:01:27.359+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-15 (offset=0)
[2025-04-14T05:01:27.757+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-16 (offset=0)
[2025-04-14T05:01:28.158+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-17 (offset=0)
[2025-04-14T05:01:28.559+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-18 (offset=0)
[2025-04-14T05:01:28.964+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-19 (offset=0)
[2025-04-14T05:01:30.404+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-20 (offset=0)
[2025-04-14T05:01:30.677+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-21 (offset=0)
[2025-04-14T05:01:31.000+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-22 (offset=0)
[2025-04-14T05:01:31.466+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-23 (offset=0)
[2025-04-14T05:01:31.849+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-24 (offset=0)
[2025-04-14T05:01:32.268+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-25 (offset=0)
[2025-04-14T05:01:32.661+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-26 (offset=0)
[2025-04-14T05:01:33.079+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-27 (offset=0)
[2025-04-14T05:01:33.379+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-28 (offset=0)
[2025-04-14T05:01:33.719+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-29 (offset=0)
[2025-04-14T05:01:36.329+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-30 (offset=0)
[2025-04-14T05:01:36.844+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-01 (offset=0)
[2025-04-14T05:01:37.279+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-02 (offset=0)
[2025-04-14T05:01:37.658+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-03 (offset=0)
[2025-04-14T05:01:37.968+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-04 (offset=0)
[2025-04-14T05:01:38.251+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-05 (offset=0)
[2025-04-14T05:01:38.587+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-06 (offset=0)
[2025-04-14T05:01:39.017+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-07 (offset=0)
[2025-04-14T05:01:39.494+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-08 (offset=0)
[2025-04-14T05:01:39.946+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-09 (offset=0)
[2025-04-14T05:01:40.342+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-10 (offset=0)
[2025-04-14T05:01:40.735+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-11 (offset=0)
[2025-04-14T05:01:41.045+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-12 (offset=0)
[2025-04-14T05:01:41.188+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-13 (offset=0)
[2025-04-14T05:01:41.600+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-14 (offset=0)
[2025-04-14T05:01:41.959+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-15 (offset=0)
[2025-04-14T05:01:42.332+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-16 (offset=0)
[2025-04-14T05:01:42.702+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-17 (offset=0)
[2025-04-14T05:01:43.059+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-18 (offset=0)
[2025-04-14T05:01:43.348+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-19 (offset=0)
[2025-04-14T05:01:43.648+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-20 (offset=0)
[2025-04-14T05:01:44.057+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-21 (offset=0)
[2025-04-14T05:01:44.465+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-22 (offset=0)
[2025-04-14T05:01:44.863+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-23 (offset=0)
[2025-04-14T05:01:45.244+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-24 (offset=0)
[2025-04-14T05:01:45.643+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-25 (offset=0)
[2025-04-14T05:01:45.956+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-26 (offset=0)
[2025-04-14T05:01:46.271+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-27 (offset=0)
[2025-04-14T05:01:46.710+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-28 (offset=0)
[2025-04-14T05:01:47.126+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-29 (offset=0)
[2025-04-14T05:01:58.108+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-30 (offset=0)
[2025-04-14T05:01:58.591+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-31 (offset=0)
[2025-04-14T05:01:59.031+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-01 (offset=0)
[2025-04-14T05:01:59.334+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-02 (offset=0)
[2025-04-14T05:02:06.291+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-03 (offset=0)
[2025-04-14T05:02:06.796+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-04 (offset=0)
[2025-04-14T05:02:07.198+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-05 (offset=0)
[2025-04-14T05:02:07.615+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-06 (offset=0)
[2025-04-14T05:02:08.036+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-07 (offset=0)
[2025-04-14T05:02:08.415+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-08 (offset=0)
[2025-04-14T05:02:08.760+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-09 (offset=0)
[2025-04-14T05:02:09.083+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-10 (offset=0)
[2025-04-14T05:02:09.458+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-11 (offset=0)
[2025-04-14T05:02:09.856+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-12 (offset=0)
[2025-04-14T05:02:10.320+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-13 (offset=0)
[2025-04-14T05:02:10.733+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-14 (offset=0)
[2025-04-14T05:02:11.183+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-15 (offset=0)
[2025-04-14T05:02:11.491+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-16 (offset=0)
[2025-04-14T05:02:11.815+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-17 (offset=0)
[2025-04-14T05:02:12.242+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-18 (offset=0)
[2025-04-14T05:02:23.336+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 86, in fetch_permits
    results = client.get(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 412, in get
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 551, in _perform_request
    response = getattr(self.session, request_type)(uri, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)
[2025-04-14T05:02:23.370+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T05:02:23.370+0000] {logging_mixin.py:190} INFO - Task start:2025-04-14 05:01:04.840626+00:00 end:2025-04-14 05:02:23.369474+00:00 duration:78.528848
[2025-04-14T05:02:23.371+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): fetch_permits_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-14 04:47:21.222286+00:00: manual__2025-04-14T04:47:21.222286+00:00, state:running, queued_at: 2025-04-14 04:47:21.237333+00:00. externally triggered: True>
[2025-04-14T05:02:23.371+0000] {logging_mixin.py:190} INFO - Failure caused by HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)
[2025-04-14T05:02:23.371+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=fetch_permits_task, run_id=manual__2025-04-14T04:47:21.222286+00:00, execution_date=20250414T044721, start_date=20250414T050104, end_date=20250414T050223
[2025-04-14T05:02:23.388+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T05:02:23.389+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task fetch_permits_task (HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10); 286)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 86, in fetch_permits
    results = client.get(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 412, in get
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 551, in _perform_request
    response = getattr(self.session, request_type)(uri, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)
[2025-04-14T05:02:23.424+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T05:02:23.467+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T05:02:23.470+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
